sudo: required
dist: trusty
language: php
php:
  - 7.0
before_script:
  - composer create-project --prefer-dist laravel/lumen=5.5 blog
  - php sync.php
  - `cd blog && composer require savfx/savphp`
script:
  - `cd blog && phpunit`
