sudo: required
dist: trusty
language: php
php:
  - 7.0
before_script:
  - composer create-project --prefer-dist laravel/lumen blog
  - php sync.php
  - cd blog && composer install --no-interaction
  - cd blog && composer require savfx/savphp
script:
  - cd blog && composer test
